### ISSUE TITLE
QFontDatabase: Cannot find font directory

### ISSUE THREAD

**Issue by gf712** [hunter-packages/Qt#14]
Hi!
I am using Hunter (0.19.125) to build Qt5 for a project and I am getting an error with the fonts at runtime: 

`QFontDatabase: Cannot find font directory $HOME/.hunter/_Base/371aef6/51136b1/f0b9fa5/Build/Qt/__qtbase/Build/lib/fonts - is Qt installed correctly?`

I can fix this (at runtime) with:
`export QT_QPA_FONTDIR=$HOME/.hunter/_Base/371aef6/51136b1/f0b9fa5/Install/lib/fonts`

Should the fonts directory be moved/copied at build time to the Build directory of hunter? Is this a bug or an expected behaviour?

I am building the project on a Ubuntu 14.10 distribution.

Thank you!

**Comment by ruslo** [comment]
> Cannot find font directory $HOME/.hunter/_Base/371aef6/51136b1/f0b9fa5/Build/Qt/__qtbase/Build/lib/fonts - is Qt installed correctly?

It's a temporary directory used by Hunter. This error simply means that this part of Qt is not relocatable.

> Should the fonts directory be moved/copied at build time to the Build directory of hunter?

The fonts already installed, just a path is not correct. If that's what you mean.

> Is this a bug or an expected behaviour?

Hunter designed so that responsibility for creating relocatable files is on package side. But it's possible to trigger extra logic to patch the installed files. You can take a look at Qt build scheme if you know how to do the fix.

As for the workaround you can take a look at `qt.conf` feature. These examples/docs might be helpful:
* https://github.com/ruslo/hunter/blob/master/examples/qt-camera/qt.conf
* https://github.com/ruslo/hunter/blob/master/examples/qt-camera/CMakeLists.txt
* https://doc.qt.io/qt-5/qt-conf.html

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
