### ISSUE TITLE
Rationale for packaging Qt with hunter patches

### ISSUE THREAD

**Issue by pretyman** [hunter-packages/Qt#8]
Hi Ruslan,

Did you have any rationale behind the packaging of Qt in this repository? I'm hoping to start a Qt-based app and would like to update Qt, but I'm unsure what were your intentions when needing to rebase the hunter patches into the new Qt version. 

Should I export the commits as diffs and apply to the new codebase? Or you had something else in mind?
Or maybe we should use the Qt mirror on github and patch the git submodules to point to hunter-packages?

Thanks

**Comment by ruslo** [comment]
> Did you have any rationale behind the packaging of Qt in this repository?

Same as with Boost: apply patches for Hunter.

> I'm hoping to start a Qt-based app and would like to update Qt

Update version? To 5.7?

> Should I export the commits as diffs and apply to the new codebase?

Yes.

> Or maybe we should use the Qt mirror on github and patch the git submodules to point to hunter-packages?

No, same problem as with Boost. They use submodules but do release archive with all components.

I have some troubles trying to update Qt to newer version. It may be not so trivial because they update the internal instructions of iOS build: https://github.com/headupinclouds/gatherer/issues/76#issuecomment-163844835. Also there are some patches in 5.6-hunter version that are applied (need to check) in 5.7 (Android resolution).

**Comment by ruslo** [comment]
Closing inactive discussion.
